Language Server - Locations - Variable (#208)
* ValidScriptDataWithLocationTests

* helper method

* include xtext.xbase.lib during tests

not needed for the tests to succeed.
HOWEVER, if a test including a Location/Range/Position FAILS, it needs
xtext/xbase/lib/util/ToStringBuilder to print the error,
otherwise the error is a NoClassDefFoundError, making the failed test incomprehensible.

* give a toString to ScriptData

* tweak assertLocationEquals
Range.equals(Object) checks for the exact class, so we need to make sure
we don't submit it a Token

* spotless...

* Variable locations