Language Server - location tests base (#204)
* ValidScriptDataWithLocationTests

* helper method

* include xtext.xbase.lib during tests

not needed for the tests to succeed.
HOWEVER, if a test including a Location/Range/Position FAILS, it needs
xtext/xbase/lib/util/ToStringBuilder to print the error,
otherwise the error is a NoClassDefFoundError, making the failed test incomprehensible.

* give a toString to ScriptData

* tweak assertLocationEquals
Range.equals(Object) checks for the exact class, so we need to make sure
we don't submit it a Token

* spotless...

* Also prepare Evaluable

This PR is very much ready and waiting for review.
It's just that I'm making further PRs on my side in the meantime,
and am sending content shared between many of them this way.

* Spotless

Co-authored-by: Jamie Adams <82782908+jaadams5@users.noreply.github.com>